### PR TITLE
Swap word order for assertions

### PR DESCRIPTION
**Pull request by mabdullahsari**
Hey 👋

This PR proposes a change to the names of the various `Assert` classes, namely swapping the word order.
All of the assertions read like fluent English now: `Assert (the) Form`, `Assert (the) Element` etc.

---

If this is something you'd not like to do, I would like to also suggest appending `-ion` to all classes to the substantive form of the verb assert as it also makes sense linguistically that way: `FormAssertion` `ElementAssertion` etc.

Thanks!

### CODE REVIEW

**Comment by sinnbeck** [comment]
I keep getting this wrong when I need to use the class so it's long overdue. Think I got the naming idea from inertia but for some reason left "-able" (AssertableInertia). I'll look into merging this and might also add "-ion" as suggested

**Comment by sinnbeck** [comment]
Sorry but I am just trying to figure out how to merge this correctly. Github complains that it cannot be merged, and want me to use the commandline. But the guide seems to suggest me just pulling it locally, fixing it and pushing it to main, which seems to skip the merge of this PR.

**Comment by mabdullahsari** [comment]
> Sorry but I am just trying to figure out how to merge this correctly. Github complains that it cannot be merged, and want me to use the commandline. But the guide seems to suggest me just pulling it locally, fixing it and pushing it to main, which seems to skip the merge of this PR.

No problem, I merged main into this branch and fixed the conflicts. 👍

**Comment by sinnbeck** [comment]
Thank you so much!

**Pull request merged**
